- name: Pull Prometheus Docker image
  docker_image:
    name: prom/prometheus
    tag: "{{ prometheus_version }}"
    source: pull

- name: Configure Prometheus to scrape from the dev machine
  template:
    src: prometheus.yml.j2
    dest: "/etc/prometheus/prometheus.yml"

- name: Run Prometheus container
  docker_container:
    name: prometheus
    image: prom/prometheus:{{ prometheus_version }}
    state: started
    restart_policy: always
    exposed_ports:
      - "{{ prometheus_port }}"
    published_ports:
      - "{{ prometheus_port }}:{{ prometheus_port }}"
    volumes:
      - "/etc/prometheus:/etc/prometheus"
      - "/var/lib/prometheus:/var/lib/prometheus"
    env:
      - "PROMETHEUS_WEB_LISTEN_ADDR=0.0.0.0:{{ prometheus_port }}"
