- name: Pull Grafana Docker image
  docker_image:
    name: grafana/grafana
    tag: "{{ grafana_version }}"
    source: pull

- name: Run Grafana container
  docker_container:
    name: grafana
    image: grafana/grafana:{{ grafana_version }}
    state: started
    restart_policy: always
    exposed_ports:
      - "{{ grafana_port }}"
    published_ports:
      - "{{ grafana_port }}:{{ grafana_port }}"
    env:
      - "GF_SECURITY_ADMIN_PASSWORD=admin"
