---
- name: Создание конфигурации Loki
  template:
    src: "loki-config.yml"
    dest: "{{ loki_config_dir }}/loki-config.yml"

- name: Запуск контейнера Loki
  docker_container:
    name: loki
    image: grafana/loki:{{ loki_version }}
    ports:
      - "3100:3100"
    volumes:
      - "{{ loki_config_dir }}/loki-config.yml:/etc/loki/loki-config.yml"
    state: started
    restart_policy: always
