---
- name: Установка rsyslog на рабочие машины
  apt:
    name: rsyslog
    state: present

- name: Создание конфигурации rsyslog
  template:
    src: "rsyslog.conf"
    dest: "/etc/rsyslog.conf"

- name: Перезапуск rsyslog
  service:
    name: rsyslog
    state: restarted
