---
- name: Install necessary packages
  apt:
    name: "{{ required_packages }}"
    state: present
    update_cache: yes

- name: Ensure sources.list.d directory exists
  file:
    path: "{{ sources_list_dir }}"
    state: directory
    mode: '0755'

- name: Download Jenkins key
  get_url:
    url: "{{ jenkins_key_url }}"
    dest: "{{ jenkins_key_dest }}"

- name: Create Jenkins repository file
  copy:
    dest: "{{ jenkins_repo_file }}"
    content: "{{ jenkins_repo_content }}"
    mode: '0644'

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Jenkins
  apt:
    name: jenkins
    state: present

- name: Start Jenkins service
  systemd:
    name: jenkins
    state: started
    enabled: yes

# Задачи для получения и вывода пароля администратора Jenkins
- name: Read Jenkins initial admin password
  slurp:
    src: /var/lib/jenkins/secrets/initialAdminPassword
  register: jenkins_password_raw
  when: "'gcp_test' in group_names"  # Проверяем, что хост в группе gcp_test

- name: Show Jenkins initial admin password
  debug:
    msg: "The Jenkins initial admin password is: {{ jenkins_password_raw.content | b64decode }}"
  when: "'gcp_test' in group_names"  # Проверяем, что хост в группе gcp_test
