---
- name: Убедиться, что сервис Docker установлен
  apt:
    name: docker.io
    state: present

- name: Убедиться, что сервис Docker запущен
  service:
    name: docker
    state: started
    enabled: true

- name: Установить указанный образ Promtail
  docker_image:
    name: grafana/promtail
    tag: "3.2.1"
    source: pull

- name: Создать директорию для Promtail
  file:
    path: /etc/promtail
    state: directory

- name: Создать конфигурационный файл для Promtail
  template:
    src: promtail-config.yml.j2
    dest: /etc/promtail/promtail-config.yml

- name: Запустить Promtail в Docker
  command: >
    docker run -d --name promtail
    -v /var/log:/var/log
    -v /etc/promtail/promtail-config.yml:/etc/promtail/promtail-config.yml
    grafana/promtail:3.2.1
    -config.file=/etc/promtail/promtail-config.yml
  args:
    creates: /var/run/docker.sock
