---
- name: Update apt cache before installing dependencies
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Update apt cache before installing dependencies
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install required dependencies (curl, Docker, Minikube)
  apt:
    name:
      - curl
      - apt-transport-https
      - ca-certificates
      - software-properties-common
    state: present
