apiVersion: 1
datasources:
  - name: Elasticsearch
    type: elasticsearch
    url: http://elasticsearch:9200
    access: proxy
    jsonData:
      timeField: "@timestamp"
    database: "[filebeat-]YYYY.MM.DD"
