replicaCount: 1

image:
  repository: zokmi4/diplom
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080
  targetPort: 8080
  nodePort: 32222
resources: {}

ingress:
  enabled: true
  annotations: {} 
  host: 34.134.198.174.nip.io
  path: /
  tls: []
  
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
