---
- name: Убедиться, что сервис Docker запущен
  service:
    name: docker
    state: started
    enabled: true

- name: Создать необходимые директории
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /opt/docker-compose
    - /opt/docker-compose/grafana

- name: Скопировать файлы конфигураций и шаблоны
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: 'files/docker-compose.yml', dest: '/opt/docker-compose/docker-compose.yml' }
    - { src: 'files/loki-config.yml', dest: '/opt/docker-compose/loki-config.yml' }

- name: Настроить файлы шаблонов
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: 'templates/prometheus.yml.j2', dest: '/opt/docker-compose/prometheus.yml' }
    - { src: 'templates/grafana.ini.j2', dest: '/opt/docker-compose/grafana/grafana.ini' }
  when: inventory_hostname == "34.56.209.145"

- name: Создать Dockerfile для Node Exporter
  copy:
    content: |
      FROM prom/node-exporter:latest
      EXPOSE 9100
      ENTRYPOINT [ "/bin/node_exporter" ]
    dest: /opt/docker-compose/Dockerfile

- name: Создать Docker Compose сервис для Node Exporter
  copy:
    content: |
      version: '3'
      services:
        node-exporter:
          build: .
          ports:
            - "9100:9100"
          restart: always
    dest: /opt/docker-compose/docker-compose.yml

- name: Запустить Docker Compose
  command: docker-compose up -d
  args:
    chdir: /opt/docker-compose

- name: Подождать, пока сервисы запустятся
  wait_for:
    timeout: 30
