- name: Убедиться, что сервис Docker запущен
  service:
    name: docker
    state: started
    enabled: true

- name: Удалить существующие контейнеры
  command: docker rm -f {{ item }}
  ignore_errors: yes
  loop:
    - prometheus
    - grafana
    - loki
    - node-exporter

- name: Создать необходимые директории
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /etc/docker-compose
    - /etc/docker-compose/grafana

- name: Скопировать файлы конфигураций и шаблоны
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: 'files/docker-compose.yml', dest: '/etc/docker-compose/docker-compose.yml' }
    - { src: 'files/loki-config.yml', dest: '/etc/docker-compose/loki-config.yml' }

- name: Настроить файлы шаблонов
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: 'templates/prometheus.yml.j2', dest: '/etc/docker-compose/prometheus.yml' }
    - { src: 'templates/grafana.ini.j2', dest: '/etc/docker-compose/grafana/grafana.ini' }

- name: Запустить Docker Compose
  command: docker-compose up -d
  args:
    chdir: /etc/docker-compose
