---
- name: Убедиться, что сервис Docker запущен
  service:
    name: docker
    state: started
    enabled: true

- name: Настроить Docker Compose для прод и тест машин
  copy:
    src: docker-compose.yml
    dest: /etc/docker-compose/docker-compose.yml

- name: Настроить Prometheus и Loki на прод и тест машинах
  template:
    src: prometheus.yml.j2
    dest: /etc/docker-compose/prometheus.yml

- name: Запустить Docker Compose на прод и тест машинах
  command: docker-compose up -d
  args:
    chdir: /etc/docker-compose

- name: Подождать, пока сервисы запустятся на прод и тест машинах
  wait_for:
    timeout: 30
