---
- name: Create Prometheus configuration directory
  ansible.builtin.file:
    path: /etc/prometheus
    state: directory

- name: Deploy Prometheus configuration
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml

- name: Install Prometheus
  shell: |
    docker run -d \
      --name=prometheus \
      -p 9090:9090 \
      -v /etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml \
      prom/prometheus:{{ prometheus_version }}
  notify: Restart Prometheus
