---
- name: Create Logstash configuration directory
  ansible.builtin.file:
    path: /etc/logstash/conf.d
    state: directory

- name: Deploy Logstash configuration
  ansible.builtin.template:
    src: logstash.conf.j2
    dest: /etc/logstash/conf.d/logstash.conf

- name: Install Logstash
  shell: |
    docker run -d \
      --name=logstash \
      -p 5044:5044 \
      -v /etc/logstash/conf.d/logstash.conf:/usr/share/logstash/pipeline/logstash.conf \
      docker.elastic.co/logstash/logstash:{{ logstash_version }}
  notify: Restart Logstash
