---
    - name: Ensure Docker Compose is installed
      apt:
        name: docker-compose
        state: present

    - name: Clean and recreate Docker Compose directory
      file:
        path: /etc/docker-compose
        state: absent
      become: true
      tags: cleanup

    - name: Create Docker Compose directory
      file:
        path: /etc/docker-compose
        state: directory
        mode: '0755'
      tags: recreate

    - name: Copy Docker Compose file
      template:
        src: docker-compose.yml.j2
        dest: /etc/docker-compose/docker-compose.yml
        mode: '0644'
      
    - name: Start Docker Compose services
      command: docker-compose -f /etc/docker-compose/docker-compose.yml up -d
