---
# Define variables for Jenkins here
required_packages:
  - openjdk-11-jre
  - wget
  - apt-transport-https

sources_list_dir: /etc/apt/sources.list.d

jenkins_key_url: "https://pkg.jenkins.io/debian/jenkins.io.key"
jenkins_key_dest: "/usr/share/keyrings/jenkins.asc"

jenkins_repo_file: "/etc/apt/sources.list.d/jenkins.list"
jenkins_repo_content: |
  deb [signed-by=/usr/share/keyrings/jenkins.asc] https://pkg.jenkins.io/debian/ stable main
