---
- name: Install Kubernetes tools (kubectl)
  shell: |
    curl -LO "https://storage.googleapis.com/kubernetes-release/release/v1.23.0/bin/linux/amd64/kubectl"
    chmod +x kubectl
    mv kubectl /usr/local/bin/
  when: ansible_hostname == "prod"

- name: Configure Kubernetes for GitLab Runner
  shell: |
    kubectl config use-context minikube
    kubectl apply -f https://gitlab.com/gitlab-org/gitlab-runner/raw/main/kubernetes/helm/gitlab-runner/templates/deployment.yaml
  when: ansible_hostname == "prod"
