---
- name: Install necessary packages
  ansible.builtin.package:
    name: 
      - docker
      - docker-compose
      - python3-pip
    state: present

- name: Start Docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
