auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /var/loki
  storage_config:
    boltdb_shipper:
      active_index_directory: /var/loki/index
      cache_location: /var/loki/cache
    filesystem:
      directory: /var/loki/chunks

fluentd:
  port: 24224
