---
- name: Установить rsyslog
  apt:
    name: rsyslog
    state: present
  become: true

- name: Проверить наличие группы syslog
  command: getent group syslog
  register: group_result
  ignore_errors: true

- name: Создать группу syslog, если не существует
  group:
    name: syslog
    state: present
  when: group_result.rc != 0
  become: true

- name: Проверить наличие пользователя syslog
  command: id syslog
  register: user_result
  ignore_errors: true

- name: Создать пользователя syslog, если не существует
  user:
    name: syslog
    group: syslog
    shell: /bin/bash
    state: present
  when: user_result.rc != 0
  become: true

- name: Перезапустить rsyslog
  service:
    name: rsyslog
    state: restarted
  become: true
