---
- name: Install GitLab Runner
  shell: |
    curl -L --output /tmp/gitlab-runner.deb https://gitlab-runner-downloads.s3.amazonaws.com/latest/debian/gitlab-runner_amd64.deb
    sudo dpkg -i /tmp/gitlab-runner.deb
  args:
    creates: /usr/local/bin/gitlab-runner

- name: Get GitLab Runner registration token
  uri:
    url: "http://{{ inventory_hostname }}/api/v4/runners"
    method: POST
    user: "root"
    password: "{{ gitlab_root_password }}"
    headers:
      Content-Type: "application/json"
    body: '{"description": "Runner for {{ inventory_hostname }}", "tag_list": "dev, test, prod"}'
    body_format: json
    return_content: yes
  register: gitlab_token_response

- name: Set GitLab Runner registration token variable
  set_fact:
    gitlab_runner_token: "{{ gitlab_token_response.json.token }}"

- name: Register GitLab Runner
  shell: |
    sudo gitlab-runner register --url http://{{ inventory_hostname }} --registration-token "{{ gitlab_runner_token }}" --executor docker --docker-image "docker:latest" --description "{{ inventory_hostname }}-runner"
  when: gitlab_runner_token is defined
