global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'nodes'
    static_configs:
      - targets: ['34.134.198.174:9100', '34.29.56.124:9100', '34.135.233.205:9100']
