---
- name: Install Docker and Docker Compose
  apt:
    name:
      - docker.io
      - docker-compose
    state: present
  notify:
    - Start Docker

- name: Install Docker Compose (prod only)
  shell: |
    curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    chmod +x /usr/local/bin/docker-compose
  when: ansible_hostname == "prod"

- name: Add user to docker group (non-prod)
  user:
    name: "{{ ansible_user }}"
    group: docker
  when: ansible_hostname != "prod"
