---
- name: Install Docker and Docker Compose
  apt:
    name:
      - docker.io
      - docker-compose
    state: present
  notify:
    - Start Docker

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    group: docker

- name: Start Docker
  systemd:
    name: docker
    state: started
    enabled: yes
