---
- name: Setup Prometheus, Loki, and ELK
  hosts: gcp_dev, gcp_prod, gcp_test
  become: true
  tasks:
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true

- name: Deploy Grafana and leading Kibana only on gcp_dev
  hosts: gcp_dev
  become: true
  tasks:
    - name: Deploy Prometheus, Grafana, Loki, and ELK
      shell: |
        docker-compose -f /home/{{ ansible_user }}/diplom/monitoring-stack/docker-compose-dev.yml up -d
      args:
        chdir: /home/{{ ansible_user }}/diplom/monitoring-stack

    - name: Copy Grafana provisioning files
      copy:
        src: /monitoring_logging/grafana/provisioning/
        dest: /home/{{ ansible_user }}/diplom/monitoring-stack/grafana/provisioning/
        mode: 0755
        owner: {{ ansible_user }}
        group: {{ ansible_user }}
        recurse: yes

    - name: Copy Grafana dashboards
      copy:
        src: /path/to/grafana/dashboards/
        dest: /home/{{ ansible_user }}/diplom/monitoring-stack/grafana/dashboards/
        mode: 0755
        owner: {{ ansible_user }}
        group: {{ ansible_user }}
        recurse: yes

- name: Install Filebeat on all machines
  hosts: all
  become: true
  tasks:
    - name: Install Filebeat
      apt:
        name: filebeat
        state: present

    - name: Copy Filebeat configuration
      copy:
        src: /monitoring_logging/filebeat/filebeat.yml
        dest: /etc/filebeat/filebeat.yml

    - name: Start Filebeat service
      service:
        name: filebeat
        state: started
        enabled: true

  vars:
    ansible_user: zokmi4
