---
- name: Setup GitLab, GitLab Runner, Docker, Minikube, Kubernetes
  hosts: all
  become: yes
  vars_files:
    - vars/{{ ansible_hostname }}.yml

  roles:
    - docker
    - gitlab
    - gitlab_runner
    - kubernetes
    - minikube
