auth_enabled: false

server:
  http_listen_port: 3100

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://{{ grafana_host }}:3100/loki/api/v1/push

scrape_configs:
  - job_name: "varlogs"
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/remote/*.log
