- name: Запускаем Docker сервис
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

- name: Создаём директорию для мониторинга
  ansible.builtin.file:
    path: /opt/monitoring
    state: directory
    owner: zokmi4
    group: zokmi4
    mode: '0755'

- name: Копируем docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /opt/monitoring/docker-compose.yml

- name: Копируем конфиг Prometheus
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /opt/monitoring/prometheus.yml

- name: Копируем конфиг Loki
  ansible.builtin.template:
    src: loki-config.yml.j2
    dest: /opt/monitoring/loki-config.yml

- name: Останавливаем и удаляем старые контейнеры, если они существуют
  ansible.builtin.shell:
    cmd: |
      docker-compose -f /opt/monitoring/docker-compose.yml down || true
      docker ps -q --filter "name=grafana" | xargs -r docker stop || true
      docker ps -q --filter "name=prometheus" | xargs -r docker stop || true
      docker ps -q --filter "name=loki" | xargs -r docker stop || true
      docker ps -q --filter "name=node_exporter" | xargs -r docker stop || true
  args:
    chdir: /opt/monitoring
  ignore_errors: yes

- name: Запускаем стек мониторинга
  ansible.builtin.shell:
    cmd: "docker-compose -f /opt/monitoring/docker-compose.yml up -d"
  args:
    chdir: /opt/monitoring

- name: Копируем конфиг rsyslog
  ansible.builtin.template:
    src: rsyslog.conf.j2
    dest: /etc/rsyslog.d/90-loki.conf
  notify: Restart rsyslog

- name: Перезапускаем rsyslog, чтобы он начал слать логи в Loki
  ansible.builtin.service:
    name: rsyslog
    state: restarted
