---
- name: Скопировать конфигурационный файл rsyslog на клиентские машины
  template:
    src: rsyslog.conf.j2
    dest: /etc/rsyslog.conf
  when: inventory_hostname != "34.56.209.145"

- name: Скопировать конфигурационный файл rsyslog на дев-машину
  template:
    src: rsyslog_server.conf.j2
    dest: /etc/rsyslog.conf
  when: inventory_hostname == "34.56.209.145"

- name: Создать директорию для логов на дев-машине
  file:
    path: /var/log/remote
    state: directory
  when: inventory_hostname == "34.56.209.145"
  become: true

- name: Перезапустить rsyslog
  service:
    name: rsyslog
    state: restarted
  become: true
