---
- name: Install rsyslog
  apt:
    name: rsyslog
    state: present
  become: true

- name: Configure rsyslog on monitoring host
  block:
    - name: Ensure /etc/rsyslog.d directory exists
      file:
        path: /etc/rsyslog.d
        state: directory
      become: true

    - name: Add rsyslog config to send logs to dev host
      copy:
        dest: /etc/rsyslog.d/50-default.conf
        content: |
          *.* @@34.56.209.145:514
      become: true
  when: inventory_hostname != '34.56.209.145'

- name: Configure rsyslog on dev host
  block:
    - name: Ensure /etc/rsyslog.d directory exists
      file:
        path: /etc/rsyslog.d
        state: directory
      become: true

    - name: Add rsyslog config for receiving logs
      copy:
        dest: /etc/rsyslog.d/60-receiver.conf
        content: |
          $ModLoad imtcp
          $InputTCPServerRun 514
      become: true
  when: inventory_hostname == '34.56.209.145'

- name: Restart rsyslog service
  service:
    name: rsyslog
    state: restarted
  become: true
