apiVersion: v1
kind: Service
metadata:
  name: {{ include "diplom.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "diplom.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app.kubernetes.io/name: {{ include "diplom.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}